AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  BaseProjectName:
    Type: String
  ScheduleExpression:
    Type: String

Globals:
  Function:
    Runtime: python3.13
    Timeout: 10
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        PROJECT_NAME: !Ref ProjectName
        BASE_PROJECT_NAME: !Ref BaseProjectName
        DEFAULT_REGION: !Ref AWS::Region

Resources:

  DeleteStackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/destroy/
      Handler: delete_stack.lambda_handler
      Policies:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess


  CheckStackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/destroy/
      Handler: check_stack.lambda_handler
      Policies:
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess

  SchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/scheduler/
      Handler: scheduler.lambda_handler
      Events:
        RunSchedule:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
            Enabled: true
        RunSchedule2amIST:
          Type: Schedule
          Properties:
            Schedule: cron(30 20 * * ? *)      # static second schedule 2:00 AM IST = 20:30 (8:30 PM) UTC (previous day)
            Enabled: true
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref DestroyStateMachine
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - states:StartExecution
            Resource: !GetAtt DestroyStateMachine.Arn

  DestroyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: DeleteBackend
        States:

          DeleteBackend:
            Type: Task
            Resource: !GetAtt DeleteStackFunction.Arn
            Parameters:
              project.$: "$.project"
              stage.$: "$.stage"
              type: "backend"
            Next: WaitBackend

          WaitBackend:
            Type: Wait
            Seconds: 20
            Next: CheckBackend

          CheckBackend:
            Type: Task
            Resource: !GetAtt CheckStackFunction.Arn
            Parameters:
              project.$: "$.project"
              stage.$: "$.stage"
              type: "backend"
            Next: BackendStatus

          BackendStatus:
            Type: Choice
            Choices:
              - Variable: "$.status"
                StringEquals: "DELETE_COMPLETE"
                Next: DeleteFrontend
            Default: WaitBackend

          DeleteFrontend:
            Type: Task
            Resource: !GetAtt DeleteStackFunction.Arn
            Parameters:
              project.$: "$.project"
              stage.$: "$.stage"
              type: "frontend"
            Next: WaitFrontend

          WaitFrontend:
            Type: Wait
            Seconds: 20
            Next: CheckFrontend

          CheckFrontend:
            Type: Task
            Resource: !GetAtt CheckStackFunction.Arn
            Parameters:
              project.$: "$.project"
              stage.$: "$.stage"
              type: "frontend"
            Next: FrontendStatus

          FrontendStatus:
            Type: Choice
            Choices:
              - Variable: "$.status"
                StringEquals: "DELETE_COMPLETE"
                Next: DeleteCore
            Default: WaitFrontend

          DeleteCore:
            Type: Task
            Resource: !GetAtt DeleteStackFunction.Arn
            Parameters:
              project.$: "$.project"
              stage.$: "$.stage"
              type: "core"
            Next: WaitCore

          WaitCore:
            Type: Wait
            Seconds: 20
            Next: CheckCore

          CheckCore:
            Type: Task
            Resource: !GetAtt CheckStackFunction.Arn
            Parameters:
              project.$: "$.project"
              stage.$: "$.stage"
              type: "core"
            Next: CoreStatus

          CoreStatus:
            Type: Choice
            Choices:
              - Variable: "$.status"
                StringEquals: "DELETE_COMPLETE"
                Next: DeleteWAF
            Default: WaitCore

          DeleteWAF:
            Type: Task
            Resource: !GetAtt DeleteStackFunction.Arn
            Parameters:
              project.$: "$.project"
              stage.$: "$.stage"
              type: "waf"
            Next: WaitWAF

          WaitWAF:
            Type: Wait
            Seconds: 20
            Next: CheckWAF

          CheckWAF:
            Type: Task
            Resource: !GetAtt CheckStackFunction.Arn
            Parameters:
              project.$: "$.project"
              stage.$: "$.stage"
              type: "waf"
            Next: WAFStatus

          WAFStatus:
            Type: Choice
            Choices:
              - Variable: "$.status"
                StringEquals: "DELETE_COMPLETE"
                Next: Done
            Default: WaitWAF

          Done:
            Type: Succeed

      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref DeleteStackFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CheckStackFunction
